# Project information
terra.description=A standalone Paper plugin for vanilla-like Overworld generation
terra.source=https://github.com/NullNomads/NullNomadsWorldgen
terra.issues=https://github.com/NullNomads/NullNomadsWorldgen/issues
terra.wiki=https://github.com/NullNomads/NullNomadsWorldgen
terra.license=GPL-3.0-or-later
# Gradle options
org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.warning.mode=all

