/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6.1/userguide/multi_project_builds.html
 */

rootProject.name = "Terra"
include("common:api")
include("common:implementation")

include("common:loader:config")
include("common:loader:addon")


include("common:addons:biome-provider-image")
include("common:addons:biome-provider-pipeline")
include("common:addons:biome-provider-single")

include("common:addons:chunk-generator-noise-3d")

include("common:addons:config-biome")
include("common:addons:config-carver")
include("common:addons:config-flora")
include("common:addons:config-noise-function")
include("common:addons:config-ore")
include("common:addons:config-palette")
include("common:addons:config-structure")
include("common:addons:config-tree")

include("common:addons:structure-terrascript-loader")




include("platforms:bukkit")
include("platforms:fabric")
include("platforms:region")
include("platforms:sponge")
include("platforms:forge")

pluginManagement {
    repositories {
        maven(url = "https://maven.fabricmc.net") {
            name = "Fabric"
        }
        gradlePluginPortal()
    }
}

plugins {
    id("com.gradle.enterprise") version "3.4.1"
}

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
//        publishAlwaysIf(true)
    }
}
