name: "Terra"
main: "com.dfsek.terra.bukkit.TerraBukkitPlugin"
version: "@VERSION@"
load: "STARTUP"
author: dfsek
website: "@WIKI@"
api-version: "1.13"
description: "@DESCRIPTION@"
softdepend: [ "WorldEdit" ]
commands:
  terra:
    description: "Terra base command"
    usage: "/terra "
    aliases: [ "te" ]
    permission: "terra.command"