modLoader = "javafml"
loaderVersion = "[36,)"
license = "@LICENSE@"
issueTrackerURL = "@ISSUES@"
[[mods]]
modId = "terra"
version = "@VERSION@"
displayName = "Terra"
displayURL = "@WIKI@"
authors = "dfsek & Terra contributors"
description = "@DESCRIPTION@"
[[dependencies.terra]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"